# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 吉林大学建设工程学院张文教授团队
email: litengyue@jlu.edu.cn
description: 
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: GFM
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


