# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 吉林大学建设工程学院张文教授团队
email: litengyue@jlu.edu.cn
description: 
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
# markdown: GFM
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  # - name:           "blog"
    # href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts"
  - name:           "lab teachings"
    href:           "/presentations"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html

